apiVersion: apps/v1
kind: Deployment
metadata:
  name: amazon-price-tracker
spec:
  replicas: 1 # Number of app instances to run
  selector:
    matchLabels:
      app: amazon-price-tracker
  template:
    metadata:
      labels:
        app: amazon-price-tracker
    spec:
      containers:
      - name: amazon-price-tracker
        image: 'docker.io/ajeetsingh77/price-tracker-app:latest'  # Replace with your Docker image name and tag
        ports:
        - containerPort: 5000  # Port your app listens on (matches local development)
      volumeMounts:
      - mountPath: /app
        name: your-app-volume
