apiVersion: v1
kind: Service
metadata:
  name: amazon-price-tracker-service
spec:
  selector:
    app: amazon-price-tracker
  type: ClusterIP  # ClusterIP service type
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
