apiVersion: v1
kind: Service
metadata:
  name: amazon-price-tracker-service
spec:
  selector:
    app: amazon-price-tracker
  type: NodePort
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30795  # Specify the NodePort to expose the service on
