apiVersion: v1
kind: Service
metadata:
  labels:
    app: amazon-price-tracker
    argocd.argoproj.io/instance: amazon-price-tracker
  name: amazon-price-tracker-svc
spec:
  ports:
    - port: 5000
      targetPort: 30795
  selector:
    app: amazon-price-tracker
  type: ClusterIP
